# Generated by Django 4.0.4 on 2022-04-18 11:04

import apps.planner.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Project name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('fullname', models.CharField(max_length=255, unique=True, verbose_name='Fullname')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Project state')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Team name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('fullname', models.CharField(max_length=255, unique=True, verbose_name='Fullname')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Team tech')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('week', models.DateField(validators=[apps.planner.validators.WeekDayValidator([0])], verbose_name='Week')),
                ('time', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.project')),
                ('tech', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planner.tech', verbose_name='Team Tech')),
            ],
            options={
                'unique_together': {('project', 'tech', 'week')},
            },
        ),
        migrations.AddField(
            model_name='team',
            name='tech',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planner.tech'),
        ),
        migrations.AddField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planner.projectmanager'),
        ),
        migrations.AddField(
            model_name='project',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planner.projectstate', verbose_name='Project State'),
        ),
        migrations.CreateModel(
            name='TimePlanSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Time Plan Summary',
                'verbose_name_plural': 'Time Plan Summaries',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('planner.timeplan',),
        ),
        migrations.CreateModel(
            name='TimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('week', models.DateField(validators=[apps.planner.validators.WeekDayValidator([0])], verbose_name='Week')),
                ('time', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.teammember')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.project')),
            ],
            options={
                'unique_together': {('project', 'member', 'week')},
            },
        ),
    ]
