# Generated by Django 4.0.4 on 2022-04-18 14:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelog',
            name='fact',
            field=models.FloatField(default=0.0, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
