# Generated by Django 4.0.4 on 2022-04-19 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_timelog_fact'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLogSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Time Log Summary',
                'verbose_name_plural': 'Time Log Summaries',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('planner.timelog',),
        ),
        migrations.AlterField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planner.projectmanager', verbose_name='Project manager'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Project Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planner.projectstate', verbose_name='Project state'),
        ),
        migrations.AlterField(
            model_name='projectmanager',
            name='fullname',
            field=models.CharField(max_length=255, unique=True, verbose_name='PM Fullname'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='fullname',
            field=models.CharField(max_length=255, unique=True, verbose_name='Members fullname'),
        ),
    ]
